version: "3.12"
services:
    api:
      build: . #take image from local folder
#      image: sloppynetworks/fastapi #download docker image from dockerhub site for example sloppynetworks/fastapi
      container_name: prod_api
      ports:
        - "80:8000"
#      command: uvicorn app.main:app --host 0.0.0.0 --port 8000 '''no need to repeat with CMD command in Dockerfile'''
#      env_file:
#        - ./.env
      environment:
        - DB_HOSTNAME=${DB_HOSTNAME}
        - DB_PORT=${DB_PORT}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_NAME=${DB_NAME}
        - SECRET_KEY=${SECRET_KEY}
        - ALGORITHM=${ALGORITHM}
        - ACCESS_TOKEN_EXP_MIN=${ACCESS_TOKEN_EXPIRE-MINUTE}
      depends_on:
        - postgres

    postgres:
      image: postgres:16 #download postgres 16 image from dockerhub
      container_name: prod_db
      environment:
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_NAME=${DB_NAME}
      volumes:
        - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:




