name: Build and Deploy code

on: [push, pull_request] # run action on every push and pull requests
#  push: # run on push
#    branches: # run only in specified branch(ies)
#      - "main" # run when push in main branch
#      - "proj-working" # or run when push in proj-working branch
#  pull_request: # run on pull_request
#    branches: # run in specified branch(ies)
#      - "test-branch" # run when pull in test-branch
#

jobs:
  job1:
    name: Run deploy on ubuntu
    runs-on: ubuntu-22.04 # specify OS for running machine.

    steps: #
      - name: pulling git repo
        users: actions/checkout@v6 # import image checkout v.6 from github repo.
        run: echo "hello"





#name: GitHub Actions Demo
#run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
#on: [push]
#jobs:
#  Explore-GitHub-Actions:
#    runs-on: ubuntu-latest
#    steps:
#      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
#      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#      - name: Check out repository code
#        uses: actions/checkout@v5
#      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
#      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
#      - name: List files in the repository
#        run: |
#          ls ${{ github.workspace }}
#      - run: echo "🍏 This job's status is ${{ job.status }}."